version: '3.4'

services:
  users-service:
    container_name: users-service
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000 # HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
